services:
  backend:
    build: ./Backend
    container_name: backend-app
    ports:
      - "8080:8080"
    env_file:
      - ./Backend/.env

  frontend:
    build: ./Frontend
    container_name: frontend-app
    ports:
      - "3000:3000"
    depends_on:
      - backend