services:
  backend:
    build: ./Backend
    container_name: backend-app
    ports:
      - "8080:8080"
    env_file:
      - ./Backend/.env

  frontend:
    build: ./Frontend
    container_name: frontend-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - ./init-dump:/init-dump
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mongo-data:/data/db

volumes:
  mongo-data: