services:
  backend:
    build: ./Backend
    container_name: backend-app
    ports:
      - "8080:8080"
    env_file:
      - ./Backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./Frontend
    container_name: frontend-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
      
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: